### ISSUE TITLE
Help Assignment7

### ISSUE THREAD

**Issue by ten12334** [knackepizza/CSE_1322_L#1]
[Assignment 7 HexadecimalCalculator.pdf](https://github.com/knackepizza/CSE_1322_L/files/5313764/Assignment.7.HexadecimalCalculator.pdf)

I need help with this assignment, I was able to try and get Lab 7, but i have a big problem with this one.

**Comment by zoty-united** [comment]
Sure, if you want to talk more about it, contact me on Discord: No?#1659

**Comment by zoty-united** [comment]
Also, @ten12334 be careful with my code. I only post my code after it's due in order to stay away from the CSE Cheaters Council. Contact me or someone else to get help before the deadline.

**Comment by ten12334** [comment]
Sorry to let you know late. I figured out the code already. I do have a different issue though. Can you tell me your discord?

**Comment by zoty-united** [comment]
> No?#1659

@ten12334

**Comment by ten12334** [comment]
Alright I will send the request shortly.
